### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by nalim89** [NewDev2298/prework-study-guide#2]
## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I see a dark blue header and footer, and four boxes with a shadow

**Comment by Hungrycoddie** [comment]
like a note taking app?

**Comment by Hungrycoddie** [comment]
`
body {
    background: lightblue;
}

header, footer {
    background: lightblue;
    padding: 1em;
}

.box {
    background: white;
    padding: 1em;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
}
